import type { CatalogKind } from '../../entities/catalog-item.entity';

export interface CatalogItemSeed {
  kind: CatalogKind;
  code: string;
  label: string;
  parentCode?: string | null;
  sortOrder?: number;
  isSystem?: boolean;
}

export const CATALOG_ITEM_SEEDS: readonly CatalogItemSeed[] = [
  // Cancer stages (system)
  {
    kind: 'cancer_stage',
    code: 'STAGE_1',
    label: 'Estadio I',
    sortOrder: 10,
    isSystem: true,
  },
  {
    kind: 'cancer_stage',
    code: 'STAGE_2',
    label: 'Estadio II',
    sortOrder: 20,
    isSystem: true,
  },
  {
    kind: 'cancer_stage',
    code: 'STAGE_3',
    label: 'Estadio III',
    sortOrder: 30,
    isSystem: true,
  },
  {
    kind: 'cancer_stage',
    code: 'STAGE_4',
    label: 'Estadio IV',
    sortOrder: 40,
    isSystem: true,
  },
  {
    kind: 'cancer_stage',
    code: 'UNKNOWN',
    label: 'Desconocido / no determinado',
    sortOrder: 90,
    isSystem: true,
  },

  // Education
  {
    kind: 'education_level',
    code: 'INITIAL',
    label: 'Inicial',
    sortOrder: 10,
    isSystem: true,
  },
  {
    kind: 'education_level',
    code: 'PRIMARY_INCOMPLETE',
    label: 'Primaria incompleta',
    sortOrder: 20,
    isSystem: true,
  },
  {
    kind: 'education_level',
    code: 'PRIMARY',
    label: 'Primaria completa',
    sortOrder: 30,
    isSystem: true,
  },
  {
    kind: 'education_level',
    code: 'SECONDARY_INCOMPLETE',
    label: 'Secundaria incompleta',
    sortOrder: 40,
    isSystem: true,
  },
  {
    kind: 'education_level',
    code: 'SECONDARY',
    label: 'Secundaria completa',
    sortOrder: 50,
    isSystem: true,
  },
  {
    kind: 'education_level',
    code: 'TECHNICAL_INCOMPLETE',
    label: 'Técnico incompleto',
    sortOrder: 60,
    isSystem: true,
  },
  {
    kind: 'education_level',
    code: 'TECHNICAL',
    label: 'Técnico completo',
    sortOrder: 70,
    isSystem: true,
  },
  {
    kind: 'education_level',
    code: 'HIGHER_INCOMPLETE',
    label: 'Superior incompleta',
    sortOrder: 80,
    isSystem: true,
  },
  {
    kind: 'education_level',
    code: 'HIGHER',
    label: 'Superior completa',
    sortOrder: 90,
    isSystem: true,
  },
  {
    kind: 'education_level',
    code: 'NONE',
    label: 'Sin instrucción formal',
    sortOrder: 100,
    isSystem: true,
  },

  // Insurance
  {
    kind: 'insurance_type',
    code: 'SIS',
    label: 'SIS',
    sortOrder: 10,
    isSystem: true,
  },
  {
    kind: 'insurance_type',
    code: 'ESSALUD',
    label: 'EsSalud',
    sortOrder: 20,
    isSystem: true,
  },
  {
    kind: 'insurance_type',
    code: 'EPS',
    label: 'EPS',
    sortOrder: 30,
    isSystem: true,
  },
  {
    kind: 'insurance_type',
    code: 'FUERZAS_ARMADAS',
    label: 'Fuerzas Armadas',
    sortOrder: 40,
    isSystem: true,
  },
  {
    kind: 'insurance_type',
    code: 'SALUDPOL',
    label: 'SaludPol',
    sortOrder: 50,
    isSystem: true,
  },
  {
    kind: 'insurance_type',
    code: 'NONE',
    label: 'Sin seguro',
    sortOrder: 90,
    isSystem: true,
  },

  {
    kind: 'eps_provider',
    code: 'RIMAC',
    label: 'Rímac',
    sortOrder: 10,
    isSystem: true,
  },
  {
    kind: 'eps_provider',
    code: 'PACIFICO',
    label: 'Pacífico',
    sortOrder: 20,
    isSystem: true,
  },
  {
    kind: 'eps_provider',
    code: 'MAPFRE',
    label: 'Mapfre',
    sortOrder: 30,
    isSystem: true,
  },
  {
    kind: 'eps_provider',
    code: 'SANITAS',
    label: 'Sanitas',
    sortOrder: 40,
    isSystem: true,
  },
  {
    kind: 'eps_provider',
    code: 'LA_POSITIVA',
    label: 'La Positiva',
    sortOrder: 50,
    isSystem: true,
  },
  {
    kind: 'eps_provider',
    code: 'ONCOSALUD',
    label: 'Oncosalud',
    sortOrder: 60,
    isSystem: true,
  },
  {
    kind: 'eps_provider',
    code: 'OTHER',
    label: 'Otra',
    sortOrder: 90,
    isSystem: true,
  },

  // Zone
  {
    kind: 'zone_type',
    code: 'URBANA',
    label: 'Urbana',
    sortOrder: 10,
    isSystem: true,
  },
  {
    kind: 'zone_type',
    code: 'RURAL',
    label: 'Rural',
    sortOrder: 20,
    isSystem: true,
  },

  // Health center categories
  {
    kind: 'health_center_category',
    code: 'I-1',
    label: 'I-1',
    sortOrder: 10,
    isSystem: true,
  },
  {
    kind: 'health_center_category',
    code: 'I-2',
    label: 'I-2',
    sortOrder: 20,
    isSystem: true,
  },
  {
    kind: 'health_center_category',
    code: 'I-3',
    label: 'I-3',
    sortOrder: 30,
    isSystem: true,
  },
  {
    kind: 'health_center_category',
    code: 'I-4',
    label: 'I-4',
    sortOrder: 40,
    isSystem: true,
  },
  {
    kind: 'health_center_category',
    code: 'II-1',
    label: 'II-1',
    sortOrder: 50,
    isSystem: true,
  },
  {
    kind: 'health_center_category',
    code: 'II-2',
    label: 'II-2',
    sortOrder: 60,
    isSystem: true,
  },
  {
    kind: 'health_center_category',
    code: 'II-E',
    label: 'II-E',
    sortOrder: 70,
    isSystem: true,
  },
  {
    kind: 'health_center_category',
    code: 'III-1',
    label: 'III-1',
    sortOrder: 80,
    isSystem: true,
  },
  {
    kind: 'health_center_category',
    code: 'III-E',
    label: 'III-E',
    sortOrder: 90,
    isSystem: true,
  },
  {
    kind: 'health_center_category',
    code: 'III-2',
    label: 'III-2',
    sortOrder: 100,
    isSystem: true,
  },

  // Care / treatment
  {
    kind: 'care_program',
    code: 'COPHOES',
    label: 'COPHOES',
    sortOrder: 10,
    isSystem: true,
  },
  {
    kind: 'care_program',
    code: 'PADOMI',
    label: 'PADOMI',
    sortOrder: 20,
    isSystem: true,
  },

  {
    kind: 'access_barrier',
    code: 'TRANSFER',
    label: 'Traslado / transporte',
    sortOrder: 10,
    isSystem: true,
  },
  {
    kind: 'access_barrier',
    code: 'LODGING',
    label: 'Alojamiento',
    sortOrder: 20,
    isSystem: true,
  },
  {
    kind: 'access_barrier',
    code: 'ALTERNATIVE_MEDICINE',
    label: 'Medicina alternativa',
    sortOrder: 30,
    isSystem: true,
  },
  {
    kind: 'access_barrier',
    code: 'EXCESSIVE_COST',
    label: 'Costo excesivo',
    sortOrder: 40,
    isSystem: true,
  },
  {
    kind: 'access_barrier',
    code: 'DOES_NOT_WANT_TO_START',
    label: 'No desea iniciar',
    sortOrder: 50,
    isSystem: true,
  },
  {
    kind: 'access_barrier',
    code: 'STOCKOUT',
    label: 'Desabastecimiento',
    sortOrder: 60,
    isSystem: true,
  },
  {
    kind: 'access_barrier',
    code: 'INFUSION_ROOM_INOPERATIVE',
    label: 'Sala de infusión inoperativa',
    sortOrder: 70,
    isSystem: true,
  },
  {
    kind: 'access_barrier',
    code: 'PATIENT_OVERLOAD',
    label: 'Sobrecarga de pacientes',
    sortOrder: 80,
    isSystem: true,
  },
  {
    kind: 'access_barrier',
    code: 'OTHER',
    label: 'Otra',
    sortOrder: 90,
    isSystem: true,
  },

  {
    kind: 'treatment_situation',
    code: 'EN_CURSO',
    label: 'En curso',
    sortOrder: 10,
    isSystem: true,
  },
  {
    kind: 'treatment_situation',
    code: 'PENDIENTE_DE_INICIO',
    label: 'Pendiente de inicio',
    sortOrder: 20,
    isSystem: true,
  },
  {
    kind: 'treatment_situation',
    code: 'INTERRUMPIDO',
    label: 'Interrumpido',
    sortOrder: 30,
    isSystem: true,
  },
  {
    kind: 'treatment_situation',
    code: 'FINALIZADO',
    label: 'Finalizado',
    sortOrder: 40,
    isSystem: true,
  },
  {
    kind: 'treatment_situation',
    code: 'SEARCHING',
    label: 'En búsqueda',
    sortOrder: 50,
    isSystem: true,
  },
  {
    kind: 'treatment_situation',
    code: 'ABANDONED',
    label: 'Abandonado',
    sortOrder: 60,
    isSystem: true,
  },
  {
    kind: 'treatment_situation',
    code: 'DECEASED_DURING_TREATMENT',
    label: 'Falleció durante el tratamiento',
    sortOrder: 70,
    isSystem: true,
  },
  {
    kind: 'treatment_situation',
    code: 'NOT_APPLICABLE',
    label: 'No aplica',
    sortOrder: 80,
    isSystem: true,
  },
  {
    kind: 'treatment_situation',
    code: 'REMISSION',
    label: 'Remisión',
    sortOrder: 90,
    isSystem: true,
  },

  {
    kind: 'sepa_shelter',
    code: 'FRIEDA_HELLER',
    label: 'Frieda Heller',
    sortOrder: 10,
    isSystem: true,
  },
  {
    kind: 'sepa_shelter',
    code: 'CASA_MAGIA',
    label: 'Casa Magia',
    sortOrder: 20,
    isSystem: true,
  },
  {
    kind: 'sepa_shelter',
    code: 'CASA_RONALD_MCDONALD',
    label: 'Casa Ronald McDonald',
    sortOrder: 30,
    isSystem: true,
  },
  {
    kind: 'sepa_shelter',
    code: 'INSPIRA',
    label: 'Inspira',
    sortOrder: 40,
    isSystem: true,
  },
  {
    kind: 'sepa_shelter',
    code: 'ALINEN',
    label: 'ALINEN',
    sortOrder: 50,
    isSystem: true,
  },
  {
    kind: 'sepa_shelter',
    code: 'OTHER',
    label: 'Otro',
    sortOrder: 90,
    isSystem: true,
  },

  {
    kind: 'sepa_transport',
    code: 'CRUZ_DEL_SUR',
    label: 'Cruz del Sur',
    sortOrder: 10,
    isSystem: true,
  },
  {
    kind: 'sepa_transport',
    code: 'LATAM_AVION_SOLIDARIO',
    label: 'LATAM Avión Solidario',
    sortOrder: 20,
    isSystem: true,
  },
  {
    kind: 'sepa_transport',
    code: 'OTHER',
    label: 'Otro',
    sortOrder: 90,
    isSystem: true,
  },

  {
    kind: 'program_dropout_reason',
    code: 'VOLUNTARY',
    label: 'Voluntaria',
    sortOrder: 10,
    isSystem: true,
  },
  {
    kind: 'program_dropout_reason',
    code: 'UNLOCATABLE',
    label: 'Ilocalizable',
    sortOrder: 20,
    isSystem: true,
  },
  {
    kind: 'program_dropout_reason',
    code: 'DECEASED',
    label: 'Fallecimiento',
    sortOrder: 30,
    isSystem: true,
  },
  {
    kind: 'program_dropout_reason',
    code: 'OTHER',
    label: 'Otra',
    sortOrder: 90,
    isSystem: true,
  },

  {
    kind: 'patient_health_phase',
    code: 'CANCER_DIAGNOSIS',
    label: 'Diagnóstico de cáncer',
    sortOrder: 10,
    isSystem: true,
  },
  {
    kind: 'patient_health_phase',
    code: 'ANNUAL_CHECKUP',
    label: 'Control anual',
    sortOrder: 20,
    isSystem: true,
  },
  {
    kind: 'patient_health_phase',
    code: 'SIGNS_AND_SYMPTOMS',
    label: 'Signos y síntomas',
    sortOrder: 30,
    isSystem: true,
  },

  {
    kind: 'patient_health_subcategory',
    code: 'SIGNS_AND_SYMPTOMS_PATIENT',
    label: 'Paciente con signos y síntomas',
    sortOrder: 10,
    isSystem: true,
  },
  {
    kind: 'patient_health_subcategory',
    code: 'ACTIVE_TREATMENT',
    label: 'Tratamiento activo',
    sortOrder: 20,
    isSystem: true,
  },
  {
    kind: 'patient_health_subcategory',
    code: 'UNDER_CONTROLS',
    label: 'En controles',
    sortOrder: 30,
    isSystem: true,
  },
  {
    kind: 'patient_health_subcategory',
    code: 'TREATMENT_ABANDONED',
    label: 'Tratamiento abandonado',
    sortOrder: 40,
    isSystem: true,
  },
  {
    kind: 'patient_health_subcategory',
    code: 'PALLIATIVE_NO_ACTIVE_TREATMENT',
    label: 'Paliativo sin tratamiento activo',
    sortOrder: 50,
    isSystem: true,
  },
  {
    kind: 'patient_health_subcategory',
    code: 'CANCER_RULED_OUT',
    label: 'Cáncer descartado',
    sortOrder: 60,
    isSystem: true,
  },

  // Open catalogs
  {
    kind: 'native_language',
    code: 'CASTELLANO',
    label: 'Castellano',
    sortOrder: 10,
  },
  { kind: 'native_language', code: 'QUECHUA', label: 'Quechua', sortOrder: 20 },
  { kind: 'native_language', code: 'AIMARA', label: 'Aimara', sortOrder: 30 },
  {
    kind: 'native_language',
    code: 'SHIPIBO_KONIBO',
    label: 'Shipibo-konibo',
    sortOrder: 40,
  },
  {
    kind: 'native_language',
    code: 'ASHANINKA',
    label: 'Asháninka',
    sortOrder: 50,
  },
  { kind: 'native_language', code: 'AWAJUN', label: 'Awajún', sortOrder: 60 },
  { kind: 'native_language', code: 'OTHER', label: 'Otra', sortOrder: 90 },

  {
    kind: 'medical_specialty',
    code: 'ONCOLOGIA_MEDICA',
    label: 'Oncología médica',
    sortOrder: 10,
  },
  {
    kind: 'medical_specialty',
    code: 'ONCOLOGIA_QUIRURGICA',
    label: 'Oncología quirúrgica',
    sortOrder: 20,
  },
  {
    kind: 'medical_specialty',
    code: 'GINECOLOGIA_ONCOLOGICA',
    label: 'Ginecología oncológica',
    sortOrder: 30,
  },
  {
    kind: 'medical_specialty',
    code: 'UROLOGIA_ONCOLOGICA',
    label: 'Urología oncológica',
    sortOrder: 40,
  },
  {
    kind: 'medical_specialty',
    code: 'HEMATOLOGIA',
    label: 'Hematología',
    sortOrder: 50,
  },
  {
    kind: 'medical_specialty',
    code: 'RADIOTERAPIA',
    label: 'Radioterapia',
    sortOrder: 60,
  },
  {
    kind: 'medical_specialty',
    code: 'MEDICINA_DEL_DOLOR',
    label: 'Medicina del dolor',
    sortOrder: 70,
  },
  {
    kind: 'medical_specialty',
    code: 'CUIDADOS_PALIATIVOS',
    label: 'Cuidados paliativos',
    sortOrder: 80,
  },
  {
    kind: 'medical_specialty',
    code: 'NUTRICION',
    label: 'Nutrición',
    sortOrder: 90,
  },
  {
    kind: 'medical_specialty',
    code: 'PSICOLOGIA',
    label: 'Psicología',
    sortOrder: 100,
  },
  {
    kind: 'medical_specialty',
    code: 'PSICOONCOLOGIA',
    label: 'Psicooncología',
    sortOrder: 110,
  },
  {
    kind: 'medical_specialty',
    code: 'CARDIOLOGIA',
    label: 'Cardiología',
    sortOrder: 120,
  },
  {
    kind: 'medical_specialty',
    code: 'GASTROENTEROLOGIA',
    label: 'Gastroenterología',
    sortOrder: 130,
  },
  {
    kind: 'medical_specialty',
    code: 'ENDOCRINOLOGIA_ONCOLOGICA',
    label: 'Endocrinología oncológica',
    sortOrder: 140,
  },

  {
    kind: 'cancer_diagnosis',
    code: 'MAMA_DUCTAL',
    label: 'Cáncer de mama ductal infiltrante',
    sortOrder: 10,
  },
  {
    kind: 'cancer_diagnosis',
    code: 'CUELLO_UTERINO',
    label: 'Cáncer de cuello uterino',
    sortOrder: 20,
  },
  {
    kind: 'cancer_diagnosis',
    code: 'GASTRICO',
    label: 'Cáncer gástrico',
    sortOrder: 30,
  },
  {
    kind: 'cancer_diagnosis',
    code: 'PROSTATA',
    label: 'Cáncer de próstata',
    sortOrder: 40,
  },
  {
    kind: 'cancer_diagnosis',
    code: 'COLON',
    label: 'Cáncer de colon',
    sortOrder: 50,
  },
  {
    kind: 'cancer_diagnosis',
    code: 'RECTO',
    label: 'Cáncer de recto',
    sortOrder: 60,
  },
  {
    kind: 'cancer_diagnosis',
    code: 'PULMON_NO_MICROCITICO',
    label: 'Cáncer de pulmón no microcítico',
    sortOrder: 70,
  },
  {
    kind: 'cancer_diagnosis',
    code: 'PULMON_MICROCITICO',
    label: 'Cáncer de pulmón microcítico',
    sortOrder: 80,
  },
  {
    kind: 'cancer_diagnosis',
    code: 'TIROIDES_PAPILAR',
    label: 'Cáncer de tiroides papilar',
    sortOrder: 90,
  },
  {
    kind: 'cancer_diagnosis',
    code: 'OVARIO',
    label: 'Cáncer de ovario',
    sortOrder: 100,
  },
  {
    kind: 'cancer_diagnosis',
    code: 'ENDOMETRIO',
    label: 'Cáncer de endometrio',
    sortOrder: 110,
  },
  {
    kind: 'cancer_diagnosis',
    code: 'LINFOMANH',
    label: 'Linfoma no Hodgkin',
    sortOrder: 120,
  },
  {
    kind: 'cancer_diagnosis',
    code: 'LINFOMAH',
    label: 'Linfoma Hodgkin',
    sortOrder: 130,
  },
  {
    kind: 'cancer_diagnosis',
    code: 'LMA',
    label: 'Leucemia mieloide aguda',
    sortOrder: 140,
  },
  {
    kind: 'cancer_diagnosis',
    code: 'LLA',
    label: 'Leucemia linfoblástica aguda',
    sortOrder: 150,
  },
  {
    kind: 'cancer_diagnosis',
    code: 'LLC',
    label: 'Leucemia linfocítica crónica',
    sortOrder: 160,
  },
  {
    kind: 'cancer_diagnosis',
    code: 'PIEL_MELANOMA',
    label: 'Melanoma',
    sortOrder: 170,
  },
  {
    kind: 'cancer_diagnosis',
    code: 'PIEL_NO_MELANOMA',
    label: 'Cáncer de piel no melanoma',
    sortOrder: 180,
  },
  {
    kind: 'cancer_diagnosis',
    code: 'PANCREAS',
    label: 'Cáncer de páncreas',
    sortOrder: 190,
  },
  {
    kind: 'cancer_diagnosis',
    code: 'HIGADO',
    label: 'Cáncer de hígado',
    sortOrder: 200,
  },
  {
    kind: 'cancer_diagnosis',
    code: 'RIÑON',
    label: 'Cáncer de riñón',
    sortOrder: 210,
  },
  {
    kind: 'cancer_diagnosis',
    code: 'VEJIGA',
    label: 'Cáncer de vejiga',
    sortOrder: 220,
  },
  {
    kind: 'cancer_diagnosis',
    code: 'OTRO',
    label: 'Otro diagnóstico oncológico',
    sortOrder: 900,
  },

  {
    kind: 'treatment_type',
    code: 'QUIMIOTERAPIA',
    label: 'Quimioterapia',
    sortOrder: 10,
  },
  {
    kind: 'treatment_type',
    code: 'RADIOTERAPIA',
    label: 'Radioterapia',
    sortOrder: 20,
  },
  { kind: 'treatment_type', code: 'CIRUGIA', label: 'Cirugía', sortOrder: 30 },
  {
    kind: 'treatment_type',
    code: 'HORMONOTERAPIA',
    label: 'Hormonoterapia',
    sortOrder: 40,
  },
  {
    kind: 'treatment_type',
    code: 'INMUNOTERAPIA',
    label: 'Inmunoterapia',
    sortOrder: 50,
  },
  {
    kind: 'treatment_type',
    code: 'TERAPIA_DIRIGIDA',
    label: 'Terapia dirigida',
    sortOrder: 60,
  },
  {
    kind: 'treatment_type',
    code: 'BRAQUITERAPIA',
    label: 'Braquiterapia',
    sortOrder: 70,
  },
  {
    kind: 'treatment_type',
    code: 'CUIDADOS_PALIATIVOS',
    label: 'Cuidados paliativos',
    sortOrder: 80,
  },
  { kind: 'treatment_type', code: 'OTRO', label: 'Otro', sortOrder: 90 },

  // Entry sources
  {
    kind: 'entry_source',
    code: 'REDES_SOCIALES',
    label: 'Redes sociales',
    sortOrder: 10,
  },
  { kind: 'entry_source', code: 'REFERIDO', label: 'Referido', sortOrder: 20 },
  { kind: 'entry_source', code: 'HOSPITAL', label: 'Hospital', sortOrder: 30 },
  { kind: 'entry_source', code: 'CAMPANA', label: 'Campaña', sortOrder: 40 },
  {
    kind: 'entry_source',
    code: 'LINEA_TELEFONICA',
    label: 'Línea telefónica',
    sortOrder: 50,
  },

  {
    kind: 'entry_sub_source',
    code: 'FACEBOOK',
    label: 'Facebook',
    parentCode: 'REDES_SOCIALES',
    sortOrder: 10,
  },
  {
    kind: 'entry_sub_source',
    code: 'INSTAGRAM',
    label: 'Instagram',
    parentCode: 'REDES_SOCIALES',
    sortOrder: 20,
  },
  {
    kind: 'entry_sub_source',
    code: 'TIKTOK',
    label: 'TikTok',
    parentCode: 'REDES_SOCIALES',
    sortOrder: 30,
  },
  {
    kind: 'entry_sub_source',
    code: 'OTRO_PACIENTE',
    label: 'Otro paciente',
    parentCode: 'REFERIDO',
    sortOrder: 10,
  },
  {
    kind: 'entry_sub_source',
    code: 'FAMILIAR',
    label: 'Familiar',
    parentCode: 'REFERIDO',
    sortOrder: 20,
  },
  {
    kind: 'entry_sub_source',
    code: 'AMIGO',
    label: 'Amigo',
    parentCode: 'REFERIDO',
    sortOrder: 30,
  },
  {
    kind: 'entry_sub_source',
    code: 'TRABAJO_SOCIAL',
    label: 'Trabajo social',
    parentCode: 'HOSPITAL',
    sortOrder: 10,
  },
  {
    kind: 'entry_sub_source',
    code: 'CONSULTA_EXTERNA',
    label: 'Consulta externa',
    parentCode: 'HOSPITAL',
    sortOrder: 20,
  },
  {
    kind: 'entry_sub_source',
    code: 'ADMISION',
    label: 'Admisión',
    parentCode: 'HOSPITAL',
    sortOrder: 30,
  },
  {
    kind: 'entry_sub_source',
    code: 'FERIA_DE_SALUD',
    label: 'Feria de salud',
    parentCode: 'CAMPANA',
    sortOrder: 10,
  },
  {
    kind: 'entry_sub_source',
    code: 'CHARLA_COMUNITARIA',
    label: 'Charla comunitaria',
    parentCode: 'CAMPANA',
    sortOrder: 20,
  },
  {
    kind: 'entry_sub_source',
    code: 'LLAMADA_ENTRANTE',
    label: 'Llamada entrante',
    parentCode: 'LINEA_TELEFONICA',
    sortOrder: 10,
  },
  {
    kind: 'entry_sub_source',
    code: 'WHATSAPP',
    label: 'WhatsApp',
    parentCode: 'LINEA_TELEFONICA',
    sortOrder: 20,
  },
];
