import type { PeruDepartment } from '../../entities/health-center.entity';

export interface UbigeoDepartmentSeed {
  code: PeruDepartment;
  ineiCode: string;
  name: string;
  sortOrder: number;
}

export interface UbigeoProvinceSeed {
  ineiCode: string;
  departmentCode: PeruDepartment;
  name: string;
  sortOrder?: number;
}

export interface UbigeoDistrictSeed {
  ineiCode: string;
  provinceIneiCode: string;
  name: string;
  sortOrder?: number;
}

export const UBIGEO_DEPARTMENTS: readonly UbigeoDepartmentSeed[] = [
  { code: 'AMAZONAS', ineiCode: '01', name: 'Amazonas', sortOrder: 1 },
  { code: 'ANCASH', ineiCode: '02', name: 'Áncash', sortOrder: 2 },
  { code: 'APURIMAC', ineiCode: '03', name: 'Apurímac', sortOrder: 3 },
  { code: 'AREQUIPA', ineiCode: '04', name: 'Arequipa', sortOrder: 4 },
  { code: 'AYACUCHO', ineiCode: '05', name: 'Ayacucho', sortOrder: 5 },
  { code: 'CAJAMARCA', ineiCode: '06', name: 'Cajamarca', sortOrder: 6 },
  { code: 'CALLAO', ineiCode: '07', name: 'Callao', sortOrder: 7 },
  { code: 'CUSCO', ineiCode: '08', name: 'Cusco', sortOrder: 8 },
  { code: 'HUANCAVELICA', ineiCode: '09', name: 'Huancavelica', sortOrder: 9 },
  { code: 'HUANUCO', ineiCode: '10', name: 'Huánuco', sortOrder: 10 },
  { code: 'ICA', ineiCode: '11', name: 'Ica', sortOrder: 11 },
  { code: 'JUNIN', ineiCode: '12', name: 'Junín', sortOrder: 12 },
  { code: 'LA_LIBERTAD', ineiCode: '13', name: 'La Libertad', sortOrder: 13 },
  { code: 'LAMBAYEQUE', ineiCode: '14', name: 'Lambayeque', sortOrder: 14 },
  { code: 'LIMA', ineiCode: '15', name: 'Lima', sortOrder: 15 },
  { code: 'LORETO', ineiCode: '16', name: 'Loreto', sortOrder: 16 },
  {
    code: 'MADRE_DE_DIOS',
    ineiCode: '17',
    name: 'Madre de Dios',
    sortOrder: 17,
  },
  { code: 'MOQUEGUA', ineiCode: '18', name: 'Moquegua', sortOrder: 18 },
  { code: 'PASCO', ineiCode: '19', name: 'Pasco', sortOrder: 19 },
  { code: 'PIURA', ineiCode: '20', name: 'Piura', sortOrder: 20 },
  { code: 'PUNO', ineiCode: '21', name: 'Puno', sortOrder: 21 },
  { code: 'SAN_MARTIN', ineiCode: '22', name: 'San Martín', sortOrder: 22 },
  { code: 'TACNA', ineiCode: '23', name: 'Tacna', sortOrder: 23 },
  { code: 'TUMBES', ineiCode: '24', name: 'Tumbes', sortOrder: 24 },
  { code: 'UCAYALI', ineiCode: '25', name: 'Ucayali', sortOrder: 25 },
];

/** All INEI provinces. Lima Metropolitana = province Lima (1501). */
export const UBIGEO_PROVINCES: readonly UbigeoProvinceSeed[] = [
  // Amazonas
  { ineiCode: '0101', departmentCode: 'AMAZONAS', name: 'Chachapoyas' },
  { ineiCode: '0102', departmentCode: 'AMAZONAS', name: 'Bagua' },
  { ineiCode: '0103', departmentCode: 'AMAZONAS', name: 'Bongará' },
  { ineiCode: '0104', departmentCode: 'AMAZONAS', name: 'Condorcanqui' },
  { ineiCode: '0105', departmentCode: 'AMAZONAS', name: 'Luya' },
  {
    ineiCode: '0106',
    departmentCode: 'AMAZONAS',
    name: 'Rodríguez de Mendoza',
  },
  { ineiCode: '0107', departmentCode: 'AMAZONAS', name: 'Utcubamba' },
  // Áncash
  { ineiCode: '0201', departmentCode: 'ANCASH', name: 'Huaraz' },
  { ineiCode: '0202', departmentCode: 'ANCASH', name: 'Aija' },
  { ineiCode: '0203', departmentCode: 'ANCASH', name: 'Antonio Raymondi' },
  { ineiCode: '0204', departmentCode: 'ANCASH', name: 'Asunción' },
  { ineiCode: '0205', departmentCode: 'ANCASH', name: 'Bolognesi' },
  { ineiCode: '0206', departmentCode: 'ANCASH', name: 'Carhuaz' },
  {
    ineiCode: '0207',
    departmentCode: 'ANCASH',
    name: 'Carlos Fermín Fitzcarrald',
  },
  { ineiCode: '0208', departmentCode: 'ANCASH', name: 'Casma' },
  { ineiCode: '0209', departmentCode: 'ANCASH', name: 'Corongo' },
  { ineiCode: '0210', departmentCode: 'ANCASH', name: 'Huari' },
  { ineiCode: '0211', departmentCode: 'ANCASH', name: 'Huarmey' },
  { ineiCode: '0212', departmentCode: 'ANCASH', name: 'Huaylas' },
  { ineiCode: '0213', departmentCode: 'ANCASH', name: 'Mariscal Luzuriaga' },
  { ineiCode: '0214', departmentCode: 'ANCASH', name: 'Ocros' },
  { ineiCode: '0215', departmentCode: 'ANCASH', name: 'Pallasca' },
  { ineiCode: '0216', departmentCode: 'ANCASH', name: 'Pomabamba' },
  { ineiCode: '0217', departmentCode: 'ANCASH', name: 'Recuay' },
  { ineiCode: '0218', departmentCode: 'ANCASH', name: 'Santa' },
  { ineiCode: '0219', departmentCode: 'ANCASH', name: 'Sihuas' },
  { ineiCode: '0220', departmentCode: 'ANCASH', name: 'Yungay' },
  // Apurímac
  { ineiCode: '0301', departmentCode: 'APURIMAC', name: 'Abancay' },
  { ineiCode: '0302', departmentCode: 'APURIMAC', name: 'Andahuaylas' },
  { ineiCode: '0303', departmentCode: 'APURIMAC', name: 'Antabamba' },
  { ineiCode: '0304', departmentCode: 'APURIMAC', name: 'Aymaraes' },
  { ineiCode: '0305', departmentCode: 'APURIMAC', name: 'Cotabambas' },
  { ineiCode: '0306', departmentCode: 'APURIMAC', name: 'Chincheros' },
  { ineiCode: '0307', departmentCode: 'APURIMAC', name: 'Grau' },
  // Arequipa
  { ineiCode: '0401', departmentCode: 'AREQUIPA', name: 'Arequipa' },
  { ineiCode: '0402', departmentCode: 'AREQUIPA', name: 'Camaná' },
  { ineiCode: '0403', departmentCode: 'AREQUIPA', name: 'Caravelí' },
  { ineiCode: '0404', departmentCode: 'AREQUIPA', name: 'Castilla' },
  { ineiCode: '0405', departmentCode: 'AREQUIPA', name: 'Caylloma' },
  { ineiCode: '0406', departmentCode: 'AREQUIPA', name: 'Condesuyos' },
  { ineiCode: '0407', departmentCode: 'AREQUIPA', name: 'Islay' },
  { ineiCode: '0408', departmentCode: 'AREQUIPA', name: 'La Unión' },
  // Ayacucho
  { ineiCode: '0501', departmentCode: 'AYACUCHO', name: 'Huamanga' },
  { ineiCode: '0502', departmentCode: 'AYACUCHO', name: 'Cangallo' },
  { ineiCode: '0503', departmentCode: 'AYACUCHO', name: 'Huanca Sancos' },
  { ineiCode: '0504', departmentCode: 'AYACUCHO', name: 'Huanta' },
  { ineiCode: '0505', departmentCode: 'AYACUCHO', name: 'La Mar' },
  { ineiCode: '0506', departmentCode: 'AYACUCHO', name: 'Lucanas' },
  { ineiCode: '0507', departmentCode: 'AYACUCHO', name: 'Parinacochas' },
  {
    ineiCode: '0508',
    departmentCode: 'AYACUCHO',
    name: 'Páucar del Sara Sara',
  },
  { ineiCode: '0509', departmentCode: 'AYACUCHO', name: 'Sucre' },
  { ineiCode: '0510', departmentCode: 'AYACUCHO', name: 'Víctor Fajardo' },
  { ineiCode: '0511', departmentCode: 'AYACUCHO', name: 'Vilcas Huamán' },
  // Cajamarca
  { ineiCode: '0601', departmentCode: 'CAJAMARCA', name: 'Cajamarca' },
  { ineiCode: '0602', departmentCode: 'CAJAMARCA', name: 'Cajabamba' },
  { ineiCode: '0603', departmentCode: 'CAJAMARCA', name: 'Celendín' },
  { ineiCode: '0604', departmentCode: 'CAJAMARCA', name: 'Chota' },
  { ineiCode: '0605', departmentCode: 'CAJAMARCA', name: 'Contumazá' },
  { ineiCode: '0606', departmentCode: 'CAJAMARCA', name: 'Cutervo' },
  { ineiCode: '0607', departmentCode: 'CAJAMARCA', name: 'Hualgayoc' },
  { ineiCode: '0608', departmentCode: 'CAJAMARCA', name: 'Jaén' },
  { ineiCode: '0609', departmentCode: 'CAJAMARCA', name: 'San Ignacio' },
  { ineiCode: '0610', departmentCode: 'CAJAMARCA', name: 'San Marcos' },
  { ineiCode: '0611', departmentCode: 'CAJAMARCA', name: 'San Miguel' },
  { ineiCode: '0612', departmentCode: 'CAJAMARCA', name: 'San Pablo' },
  { ineiCode: '0613', departmentCode: 'CAJAMARCA', name: 'Santa Cruz' },
  // Callao (single province)
  { ineiCode: '0701', departmentCode: 'CALLAO', name: 'Callao' },
  // Cusco
  { ineiCode: '0801', departmentCode: 'CUSCO', name: 'Cusco' },
  { ineiCode: '0802', departmentCode: 'CUSCO', name: 'Acomayo' },
  { ineiCode: '0803', departmentCode: 'CUSCO', name: 'Anta' },
  { ineiCode: '0804', departmentCode: 'CUSCO', name: 'Calca' },
  { ineiCode: '0805', departmentCode: 'CUSCO', name: 'Canas' },
  { ineiCode: '0806', departmentCode: 'CUSCO', name: 'Canchis' },
  { ineiCode: '0807', departmentCode: 'CUSCO', name: 'Chumbivilcas' },
  { ineiCode: '0808', departmentCode: 'CUSCO', name: 'Espinar' },
  { ineiCode: '0809', departmentCode: 'CUSCO', name: 'La Convención' },
  { ineiCode: '0810', departmentCode: 'CUSCO', name: 'Paruro' },
  { ineiCode: '0811', departmentCode: 'CUSCO', name: 'Paucartambo' },
  { ineiCode: '0812', departmentCode: 'CUSCO', name: 'Quispicanchi' },
  { ineiCode: '0813', departmentCode: 'CUSCO', name: 'Urubamba' },
  // Huancavelica
  { ineiCode: '0901', departmentCode: 'HUANCAVELICA', name: 'Huancavelica' },
  { ineiCode: '0902', departmentCode: 'HUANCAVELICA', name: 'Acobamba' },
  { ineiCode: '0903', departmentCode: 'HUANCAVELICA', name: 'Angaraes' },
  { ineiCode: '0904', departmentCode: 'HUANCAVELICA', name: 'Castrovirreyna' },
  { ineiCode: '0905', departmentCode: 'HUANCAVELICA', name: 'Churcampa' },
  { ineiCode: '0906', departmentCode: 'HUANCAVELICA', name: 'Huaytará' },
  { ineiCode: '0907', departmentCode: 'HUANCAVELICA', name: 'Tayacaja' },
  // Huánuco
  { ineiCode: '1001', departmentCode: 'HUANUCO', name: 'Huánuco' },
  { ineiCode: '1002', departmentCode: 'HUANUCO', name: 'Ambo' },
  { ineiCode: '1003', departmentCode: 'HUANUCO', name: 'Dos de Mayo' },
  { ineiCode: '1004', departmentCode: 'HUANUCO', name: 'Huacaybamba' },
  { ineiCode: '1005', departmentCode: 'HUANUCO', name: 'Huamalíes' },
  { ineiCode: '1006', departmentCode: 'HUANUCO', name: 'Leoncio Prado' },
  { ineiCode: '1007', departmentCode: 'HUANUCO', name: 'Marañón' },
  { ineiCode: '1008', departmentCode: 'HUANUCO', name: 'Pachitea' },
  { ineiCode: '1009', departmentCode: 'HUANUCO', name: 'Puerto Inca' },
  { ineiCode: '1010', departmentCode: 'HUANUCO', name: 'Lauricocha' },
  { ineiCode: '1011', departmentCode: 'HUANUCO', name: 'Yarowilca' },
  // Ica
  { ineiCode: '1101', departmentCode: 'ICA', name: 'Ica' },
  { ineiCode: '1102', departmentCode: 'ICA', name: 'Chincha' },
  { ineiCode: '1103', departmentCode: 'ICA', name: 'Nazca' },
  { ineiCode: '1104', departmentCode: 'ICA', name: 'Palpa' },
  { ineiCode: '1105', departmentCode: 'ICA', name: 'Pisco' },
  // Junín
  { ineiCode: '1201', departmentCode: 'JUNIN', name: 'Huancayo' },
  { ineiCode: '1202', departmentCode: 'JUNIN', name: 'Concepción' },
  { ineiCode: '1203', departmentCode: 'JUNIN', name: 'Chanchamayo' },
  { ineiCode: '1204', departmentCode: 'JUNIN', name: 'Jauja' },
  { ineiCode: '1205', departmentCode: 'JUNIN', name: 'Junín' },
  { ineiCode: '1206', departmentCode: 'JUNIN', name: 'Satipo' },
  { ineiCode: '1207', departmentCode: 'JUNIN', name: 'Tarma' },
  { ineiCode: '1208', departmentCode: 'JUNIN', name: 'Yauli' },
  { ineiCode: '1209', departmentCode: 'JUNIN', name: 'Chupaca' },
  // La Libertad
  { ineiCode: '1301', departmentCode: 'LA_LIBERTAD', name: 'Trujillo' },
  { ineiCode: '1302', departmentCode: 'LA_LIBERTAD', name: 'Ascope' },
  { ineiCode: '1303', departmentCode: 'LA_LIBERTAD', name: 'Bolívar' },
  { ineiCode: '1304', departmentCode: 'LA_LIBERTAD', name: 'Chepén' },
  { ineiCode: '1305', departmentCode: 'LA_LIBERTAD', name: 'Julcán' },
  { ineiCode: '1306', departmentCode: 'LA_LIBERTAD', name: 'Otuzco' },
  { ineiCode: '1307', departmentCode: 'LA_LIBERTAD', name: 'Pacasmayo' },
  { ineiCode: '1308', departmentCode: 'LA_LIBERTAD', name: 'Pataz' },
  { ineiCode: '1309', departmentCode: 'LA_LIBERTAD', name: 'Sánchez Carrión' },
  {
    ineiCode: '1310',
    departmentCode: 'LA_LIBERTAD',
    name: 'Santiago de Chuco',
  },
  { ineiCode: '1311', departmentCode: 'LA_LIBERTAD', name: 'Gran Chimú' },
  { ineiCode: '1312', departmentCode: 'LA_LIBERTAD', name: 'Virú' },
  // Lambayeque
  { ineiCode: '1401', departmentCode: 'LAMBAYEQUE', name: 'Chiclayo' },
  { ineiCode: '1402', departmentCode: 'LAMBAYEQUE', name: 'Ferreñafe' },
  { ineiCode: '1403', departmentCode: 'LAMBAYEQUE', name: 'Lambayeque' },
  // Lima — 1501 is Lima Metropolitana
  { ineiCode: '1501', departmentCode: 'LIMA', name: 'Lima' },
  { ineiCode: '1502', departmentCode: 'LIMA', name: 'Barranca' },
  { ineiCode: '1503', departmentCode: 'LIMA', name: 'Cajatambo' },
  { ineiCode: '1504', departmentCode: 'LIMA', name: 'Canta' },
  { ineiCode: '1505', departmentCode: 'LIMA', name: 'Cañete' },
  { ineiCode: '1506', departmentCode: 'LIMA', name: 'Huaral' },
  { ineiCode: '1507', departmentCode: 'LIMA', name: 'Huarochirí' },
  { ineiCode: '1508', departmentCode: 'LIMA', name: 'Huaura' },
  { ineiCode: '1509', departmentCode: 'LIMA', name: 'Oyón' },
  { ineiCode: '1510', departmentCode: 'LIMA', name: 'Yauyos' },
  // Loreto
  { ineiCode: '1601', departmentCode: 'LORETO', name: 'Maynas' },
  { ineiCode: '1602', departmentCode: 'LORETO', name: 'Alto Amazonas' },
  { ineiCode: '1603', departmentCode: 'LORETO', name: 'Loreto' },
  {
    ineiCode: '1604',
    departmentCode: 'LORETO',
    name: 'Mariscal Ramón Castilla',
  },
  { ineiCode: '1605', departmentCode: 'LORETO', name: 'Requena' },
  { ineiCode: '1606', departmentCode: 'LORETO', name: 'Ucayali' },
  { ineiCode: '1607', departmentCode: 'LORETO', name: 'Datem del Marañón' },
  { ineiCode: '1608', departmentCode: 'LORETO', name: 'Putumayo' },
  // Madre de Dios
  { ineiCode: '1701', departmentCode: 'MADRE_DE_DIOS', name: 'Tambopata' },
  { ineiCode: '1702', departmentCode: 'MADRE_DE_DIOS', name: 'Manu' },
  { ineiCode: '1703', departmentCode: 'MADRE_DE_DIOS', name: 'Tahuamanu' },
  // Moquegua
  { ineiCode: '1801', departmentCode: 'MOQUEGUA', name: 'Mariscal Nieto' },
  {
    ineiCode: '1802',
    departmentCode: 'MOQUEGUA',
    name: 'General Sánchez Cerro',
  },
  { ineiCode: '1803', departmentCode: 'MOQUEGUA', name: 'Ilo' },
  // Pasco
  { ineiCode: '1901', departmentCode: 'PASCO', name: 'Pasco' },
  { ineiCode: '1902', departmentCode: 'PASCO', name: 'Daniel Alcides Carrión' },
  { ineiCode: '1903', departmentCode: 'PASCO', name: 'Oxapampa' },
  // Piura
  { ineiCode: '2001', departmentCode: 'PIURA', name: 'Piura' },
  { ineiCode: '2002', departmentCode: 'PIURA', name: 'Ayabaca' },
  { ineiCode: '2003', departmentCode: 'PIURA', name: 'Huancabamba' },
  { ineiCode: '2004', departmentCode: 'PIURA', name: 'Morropón' },
  { ineiCode: '2005', departmentCode: 'PIURA', name: 'Paita' },
  { ineiCode: '2006', departmentCode: 'PIURA', name: 'Sullana' },
  { ineiCode: '2007', departmentCode: 'PIURA', name: 'Talara' },
  { ineiCode: '2008', departmentCode: 'PIURA', name: 'Sechura' },
  // Puno
  { ineiCode: '2101', departmentCode: 'PUNO', name: 'Puno' },
  { ineiCode: '2102', departmentCode: 'PUNO', name: 'Azángaro' },
  { ineiCode: '2103', departmentCode: 'PUNO', name: 'Carabaya' },
  { ineiCode: '2104', departmentCode: 'PUNO', name: 'Chucuito' },
  { ineiCode: '2105', departmentCode: 'PUNO', name: 'El Collao' },
  { ineiCode: '2106', departmentCode: 'PUNO', name: 'Huancané' },
  { ineiCode: '2107', departmentCode: 'PUNO', name: 'Lampa' },
  { ineiCode: '2108', departmentCode: 'PUNO', name: 'Melgar' },
  { ineiCode: '2109', departmentCode: 'PUNO', name: 'Moho' },
  { ineiCode: '2110', departmentCode: 'PUNO', name: 'San Antonio de Putina' },
  { ineiCode: '2111', departmentCode: 'PUNO', name: 'San Román' },
  { ineiCode: '2112', departmentCode: 'PUNO', name: 'Sandia' },
  { ineiCode: '2113', departmentCode: 'PUNO', name: 'Yunguyo' },
  // San Martín
  { ineiCode: '2201', departmentCode: 'SAN_MARTIN', name: 'Moyobamba' },
  { ineiCode: '2202', departmentCode: 'SAN_MARTIN', name: 'Bellavista' },
  { ineiCode: '2203', departmentCode: 'SAN_MARTIN', name: 'El Dorado' },
  { ineiCode: '2204', departmentCode: 'SAN_MARTIN', name: 'Huallaga' },
  { ineiCode: '2205', departmentCode: 'SAN_MARTIN', name: 'Lamas' },
  { ineiCode: '2206', departmentCode: 'SAN_MARTIN', name: 'Mariscal Cáceres' },
  { ineiCode: '2207', departmentCode: 'SAN_MARTIN', name: 'Picota' },
  { ineiCode: '2208', departmentCode: 'SAN_MARTIN', name: 'Rioja' },
  { ineiCode: '2209', departmentCode: 'SAN_MARTIN', name: 'San Martín' },
  { ineiCode: '2210', departmentCode: 'SAN_MARTIN', name: 'Tocache' },
  // Tacna
  { ineiCode: '2301', departmentCode: 'TACNA', name: 'Tacna' },
  { ineiCode: '2302', departmentCode: 'TACNA', name: 'Candarave' },
  { ineiCode: '2303', departmentCode: 'TACNA', name: 'Jorge Basadre' },
  { ineiCode: '2304', departmentCode: 'TACNA', name: 'Tarata' },
  // Tumbes
  { ineiCode: '2401', departmentCode: 'TUMBES', name: 'Tumbes' },
  { ineiCode: '2402', departmentCode: 'TUMBES', name: 'Contralmirante Villar' },
  { ineiCode: '2403', departmentCode: 'TUMBES', name: 'Zarumilla' },
  // Ucayali
  { ineiCode: '2501', departmentCode: 'UCAYALI', name: 'Coronel Portillo' },
  { ineiCode: '2502', departmentCode: 'UCAYALI', name: 'Atalaya' },
  { ineiCode: '2503', departmentCode: 'UCAYALI', name: 'Padre Abad' },
  { ineiCode: '2504', departmentCode: 'UCAYALI', name: 'Purús' },
];

/**
 * Districts for Lima Metropolitana (1501), Callao (0701), and provincial
 * capitals nationwide. Full INEI district dump can replace this later without
 * schema changes.
 */
export const UBIGEO_DISTRICTS: readonly UbigeoDistrictSeed[] = [
  // Lima Metropolitana
  { ineiCode: '150101', provinceIneiCode: '1501', name: 'Lima' },
  { ineiCode: '150102', provinceIneiCode: '1501', name: 'Ancón' },
  { ineiCode: '150103', provinceIneiCode: '1501', name: 'Ate' },
  { ineiCode: '150104', provinceIneiCode: '1501', name: 'Barranco' },
  { ineiCode: '150105', provinceIneiCode: '1501', name: 'Breña' },
  { ineiCode: '150106', provinceIneiCode: '1501', name: 'Carabayllo' },
  { ineiCode: '150107', provinceIneiCode: '1501', name: 'Chaclacayo' },
  { ineiCode: '150108', provinceIneiCode: '1501', name: 'Chorrillos' },
  { ineiCode: '150109', provinceIneiCode: '1501', name: 'Cieneguilla' },
  { ineiCode: '150110', provinceIneiCode: '1501', name: 'Comas' },
  { ineiCode: '150111', provinceIneiCode: '1501', name: 'El Agustino' },
  { ineiCode: '150112', provinceIneiCode: '1501', name: 'Independencia' },
  { ineiCode: '150113', provinceIneiCode: '1501', name: 'Jesús María' },
  { ineiCode: '150114', provinceIneiCode: '1501', name: 'La Molina' },
  { ineiCode: '150115', provinceIneiCode: '1501', name: 'La Victoria' },
  { ineiCode: '150116', provinceIneiCode: '1501', name: 'Lince' },
  { ineiCode: '150117', provinceIneiCode: '1501', name: 'Los Olivos' },
  { ineiCode: '150118', provinceIneiCode: '1501', name: 'Lurigancho' },
  { ineiCode: '150119', provinceIneiCode: '1501', name: 'Lurín' },
  { ineiCode: '150120', provinceIneiCode: '1501', name: 'Magdalena del Mar' },
  { ineiCode: '150121', provinceIneiCode: '1501', name: 'Pueblo Libre' },
  { ineiCode: '150122', provinceIneiCode: '1501', name: 'Miraflores' },
  { ineiCode: '150123', provinceIneiCode: '1501', name: 'Pachacámac' },
  { ineiCode: '150124', provinceIneiCode: '1501', name: 'Pucusana' },
  { ineiCode: '150125', provinceIneiCode: '1501', name: 'Puente Piedra' },
  { ineiCode: '150126', provinceIneiCode: '1501', name: 'Punta Hermosa' },
  { ineiCode: '150127', provinceIneiCode: '1501', name: 'Punta Negra' },
  { ineiCode: '150128', provinceIneiCode: '1501', name: 'Rímac' },
  { ineiCode: '150129', provinceIneiCode: '1501', name: 'San Bartolo' },
  { ineiCode: '150130', provinceIneiCode: '1501', name: 'San Borja' },
  { ineiCode: '150131', provinceIneiCode: '1501', name: 'San Isidro' },
  {
    ineiCode: '150132',
    provinceIneiCode: '1501',
    name: 'San Juan de Lurigancho',
  },
  {
    ineiCode: '150133',
    provinceIneiCode: '1501',
    name: 'San Juan de Miraflores',
  },
  { ineiCode: '150134', provinceIneiCode: '1501', name: 'San Luis' },
  {
    ineiCode: '150135',
    provinceIneiCode: '1501',
    name: 'San Martín de Porres',
  },
  { ineiCode: '150136', provinceIneiCode: '1501', name: 'San Miguel' },
  { ineiCode: '150137', provinceIneiCode: '1501', name: 'Santa Anita' },
  { ineiCode: '150138', provinceIneiCode: '1501', name: 'Santa María del Mar' },
  { ineiCode: '150139', provinceIneiCode: '1501', name: 'Santa Rosa' },
  { ineiCode: '150140', provinceIneiCode: '1501', name: 'Santiago de Surco' },
  { ineiCode: '150141', provinceIneiCode: '1501', name: 'Surquillo' },
  { ineiCode: '150142', provinceIneiCode: '1501', name: 'Villa El Salvador' },
  {
    ineiCode: '150143',
    provinceIneiCode: '1501',
    name: 'Villa María del Triunfo',
  },
  // Callao
  { ineiCode: '070101', provinceIneiCode: '0701', name: 'Callao' },
  { ineiCode: '070102', provinceIneiCode: '0701', name: 'Bellavista' },
  {
    ineiCode: '070103',
    provinceIneiCode: '0701',
    name: 'Carmen de la Legua Reynoso',
  },
  { ineiCode: '070104', provinceIneiCode: '0701', name: 'La Perla' },
  { ineiCode: '070105', provinceIneiCode: '0701', name: 'La Punta' },
  { ineiCode: '070106', provinceIneiCode: '0701', name: 'Ventanilla' },
  { ineiCode: '070107', provinceIneiCode: '0701', name: 'Mi Perú' },
  // Provincial capitals (district matching province capital name / first district)
  { ineiCode: '010101', provinceIneiCode: '0101', name: 'Chachapoyas' },
  { ineiCode: '020101', provinceIneiCode: '0201', name: 'Huaraz' },
  { ineiCode: '021801', provinceIneiCode: '0218', name: 'Chimbote' },
  { ineiCode: '030101', provinceIneiCode: '0301', name: 'Abancay' },
  { ineiCode: '040101', provinceIneiCode: '0401', name: 'Arequipa' },
  { ineiCode: '040102', provinceIneiCode: '0401', name: 'Alto Selva Alegre' },
  { ineiCode: '040103', provinceIneiCode: '0401', name: 'Cayma' },
  { ineiCode: '040104', provinceIneiCode: '0401', name: 'Cerro Colorado' },
  { ineiCode: '040105', provinceIneiCode: '0401', name: 'Characato' },
  {
    ineiCode: '040109',
    provinceIneiCode: '0401',
    name: 'José Luis Bustamante y Rivero',
  },
  { ineiCode: '040112', provinceIneiCode: '0401', name: 'Miraflores' },
  { ineiCode: '040115', provinceIneiCode: '0401', name: 'Paucarpata' },
  { ineiCode: '040119', provinceIneiCode: '0401', name: 'Socabaya' },
  { ineiCode: '050101', provinceIneiCode: '0501', name: 'Ayacucho' },
  { ineiCode: '060101', provinceIneiCode: '0601', name: 'Cajamarca' },
  { ineiCode: '080101', provinceIneiCode: '0801', name: 'Cusco' },
  { ineiCode: '080102', provinceIneiCode: '0801', name: 'Ccorca' },
  { ineiCode: '080105', provinceIneiCode: '0801', name: 'San Jerónimo' },
  { ineiCode: '080106', provinceIneiCode: '0801', name: 'San Sebastián' },
  { ineiCode: '080107', provinceIneiCode: '0801', name: 'Santiago' },
  { ineiCode: '080108', provinceIneiCode: '0801', name: 'Wanchaq' },
  { ineiCode: '090101', provinceIneiCode: '0901', name: 'Huancavelica' },
  { ineiCode: '100101', provinceIneiCode: '1001', name: 'Huánuco' },
  { ineiCode: '110101', provinceIneiCode: '1101', name: 'Ica' },
  { ineiCode: '120101', provinceIneiCode: '1201', name: 'Huancayo' },
  { ineiCode: '120110', provinceIneiCode: '1201', name: 'El Tambo' },
  { ineiCode: '120113', provinceIneiCode: '1201', name: 'Chilca' },
  { ineiCode: '130101', provinceIneiCode: '1301', name: 'Trujillo' },
  { ineiCode: '130102', provinceIneiCode: '1301', name: 'El Porvenir' },
  { ineiCode: '130104', provinceIneiCode: '1301', name: 'Florencia de Mora' },
  { ineiCode: '130105', provinceIneiCode: '1301', name: 'Huanchaco' },
  { ineiCode: '130106', provinceIneiCode: '1301', name: 'La Esperanza' },
  {
    ineiCode: '130109',
    provinceIneiCode: '1301',
    name: 'Víctor Larco Herrera',
  },
  { ineiCode: '140101', provinceIneiCode: '1401', name: 'Chiclayo' },
  { ineiCode: '140105', provinceIneiCode: '1401', name: 'José Leonardo Ortiz' },
  { ineiCode: '140106', provinceIneiCode: '1401', name: 'La Victoria' },
  { ineiCode: '160101', provinceIneiCode: '1601', name: 'Iquitos' },
  { ineiCode: '160102', provinceIneiCode: '1601', name: 'Alto Nanay' },
  { ineiCode: '160108', provinceIneiCode: '1601', name: 'Belén' },
  { ineiCode: '160112', provinceIneiCode: '1601', name: 'Punchana' },
  { ineiCode: '160114', provinceIneiCode: '1601', name: 'San Juan Bautista' },
  { ineiCode: '170101', provinceIneiCode: '1701', name: 'Tambopata' },
  { ineiCode: '180101', provinceIneiCode: '1801', name: 'Moquegua' },
  { ineiCode: '190101', provinceIneiCode: '1901', name: 'Chaupimarca' },
  { ineiCode: '200101', provinceIneiCode: '2001', name: 'Piura' },
  { ineiCode: '200104', provinceIneiCode: '2001', name: 'Castilla' },
  {
    ineiCode: '200114',
    provinceIneiCode: '2001',
    name: 'Veintiséis de Octubre',
  },
  { ineiCode: '210101', provinceIneiCode: '2101', name: 'Puno' },
  { ineiCode: '211101', provinceIneiCode: '2111', name: 'Juliaca' },
  { ineiCode: '220901', provinceIneiCode: '2209', name: 'Tarapoto' },
  { ineiCode: '220101', provinceIneiCode: '2201', name: 'Moyobamba' },
  { ineiCode: '230101', provinceIneiCode: '2301', name: 'Tacna' },
  { ineiCode: '240101', provinceIneiCode: '2401', name: 'Tumbes' },
  { ineiCode: '250101', provinceIneiCode: '2501', name: 'Calleria' },
];
