export enum AccessBarrierCode {
  TRANSFER = 'TRANSFER',
  LODGING = 'LODGING',
  ALTERNATIVE_MEDICINE = 'ALTERNATIVE_MEDICINE',
  EXCESSIVE_COST = 'EXCESSIVE_COST',
  DOES_NOT_WANT_TO_START = 'DOES_NOT_WANT_TO_START',
  STOCKOUT = 'STOCKOUT',
  INFUSION_ROOM_INOPERATIVE = 'INFUSION_ROOM_INOPERATIVE',
  PATIENT_OVERLOAD = 'PATIENT_OVERLOAD',
  OTHER = 'OTHER',
}
