export enum InteractionType {
  WHATSAPP = 'WHATSAPP',
  CALL = 'CALL',
  VIDEO_CALL = 'VIDEO_CALL',
  EMAIL = 'EMAIL',
  IN_PERSON = 'IN_PERSON',
  FACEBOOK = 'FACEBOOK',
}
export enum InteractionStatus {
  SCHEDULED = 'SCHEDULED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_ANSWER = 'NO_ANSWER',
}
export enum InteractionPurpose {
  FIRST_CONTACT = 'FIRST_CONTACT',
  ENROLLMENT = 'ENROLLMENT',
  FOLLOW_UP = 'FOLLOW_UP',
  PSYCHOONCOLOGY_REFERRAL = 'PSYCHOONCOLOGY_REFERRAL',
  OTHER = 'OTHER',
}
