export enum ShelterSepaProvider {
  FRIEDA_HELLER = 'FRIEDA_HELLER',
  CASA_MAGIA = 'CASA_MAGIA',
  CASA_RONALD_MCDONALD = 'CASA_RONALD_MCDONALD',
  INSPIRA = 'INSPIRA',
  ALINEN = 'ALINEN',
  OTHER = 'OTHER',
}
