export enum TreatmentSituation {
  EN_CURSO = 'EN_CURSO',
  PENDIENTE_DE_INICIO = 'PENDIENTE_DE_INICIO',
  INTERRUMPIDO = 'INTERRUMPIDO',
  FINALIZADO = 'FINALIZADO',
  SEARCHING = 'SEARCHING',
  ABANDONED = 'ABANDONED',
  DECEASED_DURING_TREATMENT = 'DECEASED_DURING_TREATMENT',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
  REMISSION = 'REMISSION',
}
